name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - uat
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 🔥 Dynamic environment mapping
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

    steps:
      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set Image Tag
      - name: Set Tag
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
          echo "IMAGE_TAG=prod" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "uat" ]]; then
          echo "IMAGE_TAG=uat" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "dev" ]]; then
          echo "IMAGE_TAG=dev" >> $GITHUB_OUTPUT
          else
          echo "IMAGE_TAG=local" >> $GITHUB_OUTPUT
          fi

      # 3. Login Docker Hub
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 4. Build Docker Image
      - name: Build Image
        run: |
          docker build \
            --build-arg VITE_AUTH_URL=${{ secrets.VITE_AUTH_URL }} \
            --build-arg VITE_APP=${{ secrets.VITE_APP }} \
            -t hari8209/envdocker:${{ steps.env.outputs.IMAGE_TAG }} .

      # 5. Push Image
      - name: Push Image
        run: |
          docker push hari8209/envdocker:${{ steps.env.outputs.IMAGE_TAG }}
