name: CI/CD Pipeline with Observability

on:
  push:
    branches:
      - main
      - uat
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

    steps:
      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set Image Tag
      - name: Set Tag
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "IMAGE_TAG=prod" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "uat" ]]; then
            echo "IMAGE_TAG=uat" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            echo "IMAGE_TAG=dev" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=local" >> $GITHUB_OUTPUT
          fi

      # 3. Login Docker Hub
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 4. Build Image (capture logs)
      - name: Build Image
        run: |
          docker build \
            --build-arg VITE_AUTH_URL=${{ secrets.VITE_AUTH_URL }} \
            --build-arg VITE_APP=${{ secrets.VITE_APP }} \
            -t hari8209/envdocker:${{ steps.env.outputs.IMAGE_TAG }} . 2>&1 | tee build.log

      # 5. Push Image (capture logs)
      - name: Push Image
        run: |
          docker push hari8209/envdocker:${{ steps.env.outputs.IMAGE_TAG }} 2>&1 | tee -a build.log

      # 6. Send Logs to Grafana Cloud
      - name: Send Logs to Grafana Cloud
        if: always()
        run: |
          # Limit log size (IMPORTANT)
          LOG_CONTENT=$(tail -n 200 build.log | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')

          TIMESTAMP=$(date +%s%N)

          curl -v -u "${{ secrets.GRAFANA_USER }}:${{ secrets.GRAFANA_API_KEY }}" \
            -X POST "${{ secrets.GRAFANA_URL }}" \
            -H "Content-Type: application/json" \
            --data-raw "{
              \"streams\": [
                {
                  \"stream\": {
                    \"job\": \"github-actions\",
                    \"repo\": \"${{ github.repository }}\",
                    \"branch\": \"${{ github.ref_name }}\",
                    \"status\": \"${{ job.status }}\"
                  },
                  \"values\": [
                    [\"$TIMESTAMP\", \"$LOG_CONTENT\"]
                  ]
                }
              ]
            }"
